export const aboutContent = {
  title: "About Dominion Writer",
  sections: [
    {
      heading: "Write Without Limits. Create Without Compromise.",
      text: "Every great book begins with an idea.\n\nWhether you're writing your first novel, a memoir, a children's book, a screenplay, or a non-fiction masterpiece, every author deserves the freedom to develop that idea without worrying about artificial limitations, hidden costs, or restrictive software.\n\nWelcome to Dominion Writer—an AI-powered book writing platform built for authors who believe their creativity should never be constrained."
    },
    {
      heading: "Our Mission",
      text: "Our mission is simple:\n\nTo give every author complete control over their writing experience by allowing them to choose their own AI providers instead of being locked into someone else's subscription model.\n\nWe believe the best stories are written when authors have the freedom to explore every idea, expand every chapter, and refine every sentence without wondering whether they'll run out of credits before they reach \"The End.\"\n\nThat's why Dominion Writer was created."
    },
    {
      heading: "Why We Built Dominion Writer",
      text: "Artificial intelligence has transformed the way authors write, research, brainstorm, and edit. It has opened exciting new possibilities for writers around the world.\n\nUnfortunately, it has also introduced a problem.\n\nMany AI writing platforms operate using monthly subscriptions and proprietary credit systems. Authors are told they receive thousands—or even millions—of credits each month, yet very few platforms clearly explain what those credits actually mean.\n\nHow many words will those credits generate? How many chapters can you write? Will they be enough to complete your manuscript? How much will finishing your book actually cost?\n\nToo often, the answers aren't obvious until you've already invested your time and money.\n\nAt Dominion Writer, we believe authors deserve complete transparency before making those decisions.\n\nWe don't believe in hidden limitations, confusing pricing structures, or marketing that leaves important details unanswered.\n\nInstead, we believe in honesty, clarity, and giving writers complete control over the tools they use."
    },
    {
      heading: "A Different Approach to AI Writing",
      text: "Dominion Writer takes a fundamentally different approach from traditional AI writing software.\n\nInstead of purchasing AI credits from us, you simply connect your preferred AI provider using your own API key.\n\nThis means your AI usage is billed directly by the provider you choose, allowing you to understand exactly what you're paying for based on published pricing rather than an internal credit system.\n\nThere are no hidden markups. No mystery calculations. No guessing how many words your remaining credits might produce.\n\nJust complete transparency and complete control.\n\nYour creativity deserves nothing less."
    },
    {
      heading: "One AI Provider or Three Working Together",
      text: "Every author has a unique writing process.\n\nSome writers prefer one trusted AI model that handles everything from brainstorming and drafting to editing and polishing.\n\nOthers discover that different AI providers excel at different tasks.\n\nThat's why Dominion Writer supports up to three AI API providers within a single writing environment.\n\nMore importantly, these AI providers don't operate as isolated tools.\n\nThey work congruently within Dominion Writer, allowing you to build a writing workflow that combines the strengths of each model to produce the highest-quality manuscript possible.\n\nFor example, you may choose one AI for its exceptional creative storytelling, another for factual accuracy and research, and a third for refining grammar, structure, and style. Together, they become part of one seamless writing experience designed around your needs—not ours.\n\nOf course, if your preferred AI provider already delivers everything you need, that's perfectly fine too. Dominion Writer works just as effectively with a single AI API.\n\nOur platform is built around flexibility, not requirements."
    },
    {
      heading: "Built for Creativity, Not Credit Limits",
      text: "Writing a book is rarely a straight path. Characters evolve. Ideas grow. Research expands. Entire chapters may be rewritten several times before they're exactly right.\n\nAuthors shouldn't have to shorten scenes or simplify ideas simply because they're worried about exhausting a monthly credit allowance.\n\nAt Dominion Writer, we believe your imagination should determine the length of your story—not someone else's pricing model.\n\nBy allowing you to choose your own AI provider, you decide how your writing budget is managed and which AI technology best supports your creative goals.\n\nThat freedom allows you to focus on what truly matters: Writing your best book."
    },
    {
      heading: "A Lifetime Platform Designed for Authors",
      text: "Dominion Writer isn't another subscription that you'll need to keep paying for year after year.\n\nIt's a lifetime writing platform designed to grow with you throughout your writing journey.\n\nPurchase Dominion Writer once, then continue using the AI providers that best fit your needs.\n\nAs new AI technologies emerge, you're free to adopt them without waiting for us to decide which models to support or forcing you into higher-priced subscription plans.\n\nYour personal writing platform. Your AI choices belong to you. Your future remains in your hands."
    },
    {
      heading: "Export Your Book Your Way",
      text: "Creating your manuscript is only part of the publishing journey.\n\nWhen your book is finished, Dominion Writer makes it easy to prepare it for editing, sharing, printing, or publishing.\n\nYour completed manuscript can be exported in multiple professional formats, including:\n\n• Microsoft Word (.docx)\n• PDF (.pdf)\n• EPUB (.epub)\n\nWhether you're sending your manuscript to an editor, sharing it with beta readers, preparing it for print, or publishing through your favorite self-publishing platform, Dominion Writer helps ensure your work is ready for the next step."
    },
    {
      heading: "Transparency Is at the Heart of Everything We Do",
      text: "At Dominion Writer, honesty isn't simply good business. It's part of who we are.\n\nWe believe authors deserve complete information before investing in any writing software. You shouldn't have to search through fine print, compare confusing pricing charts, or investigate what a subscription really includes.\n\nOur goal is to explain everything clearly so you can make informed decisions with confidence.\n\nNo smoke and mirrors. No hidden restrictions. No surprises. Just straightforward software built for writers who value integrity as much as creativity."
    },
    {
      heading: "More Than AI Writing Software",
      text: "Dominion Writer isn't here to replace authors. It's here to empower them.\n\nArtificial intelligence is an incredible writing assistant, but your imagination, your voice, your experiences, and your storytelling remain uniquely yours.\n\nOur role is to remove unnecessary barriers so you can spend less time worrying about software limitations and more time doing what you love—creating stories that inspire, educate, entertain, and leave a lasting impact.\n\nWhether you're an aspiring novelist, an experienced author, a content creator, an educator, or an independent publisher, Dominion Writer provides the flexibility, transparency, and control you need to write with confidence."
    },
    {
      heading: "Welcome to Dominion Writer",
      text: "The future of writing belongs to authors who have freedom, flexibility, and complete control over the tools they use.\n\nDominion Writer was created for writers who believe creativity should never be limited by hidden credit systems, restrictive subscriptions, or confusing pricing models.\n\nHere, you choose your AI. You control your costs. You decide how your writing workflow is built.\n\nWhether that's one AI provider or three working together in harmony, Dominion Writer adapts to the way you write.\n\nWe're honored to be part of your creative journey and excited to help you bring your stories to life.\n\nWelcome to Dominion Writer—where transparency meets innovation, creativity has no limits, and every author has the freedom to write with confidence."
    }
  ]
}

export const privacyContent = {
  title: "Privacy Policy",
  effectiveDate: "Immediately Upon Purchase",
  contact: "admin@dominionwriter.com",
  owner: "Mr. Nghia Nguyen",
  sections: [
    { number: "1", title: "Information We Collect", items: [
      { subtitle: "Personal Information", text: "This may include: Full name, Email address, Username, Billing information processed through third-party payment providers, Account preferences, Support requests, Communication history. Dominion Writer does not intentionally collect sensitive personal information unless voluntarily provided by the user." },
      { subtitle: "Technical Information", text: "We may automatically collect information including: IP address, Browser type, Device type, Operating system, Referring website, Pages visited, Session duration, Date and time of access, Error logs, Security logs. This information helps improve platform performance, security, and user experience." },
      { subtitle: "AI API Information", text: "Dominion Writer allows users to connect their own AI API credentials. Your API credentials are used solely to facilitate communication between your account and your selected AI provider. Dominion Writer does not assume ownership of your API account and is not responsible for any activity, billing, usage, credits, or charges associated with your chosen AI provider." }
    ]},
    { number: "2", title: "How We Use Your Information", text: "Your information may be used to: Create and manage your account, Authenticate users, Provide platform functionality, Improve website performance, Respond to support requests, Detect fraud or abuse, Protect platform security, Comply with legal obligations, Maintain system integrity. We do not sell your personal information to third parties." },
    { number: "3", title: "Third-Party Services", text: "Dominion Writer relies on trusted third-party providers to deliver various services, which may include: Payment processors, Cloud hosting providers, Analytics services, Email service providers, Security services, AI providers selected by users. Each third-party provider maintains its own privacy practices and policies. Dominion Writer is not responsible for the privacy practices, billing policies, security, or data handling of third-party services." },
    { number: "4", title: "User Content", text: "Users are solely responsible for the content they create, edit, upload, generate, or publish using Dominion Writer. Content generated through your connected AI provider remains your responsibility. Dominion Writer does not routinely monitor, review, endorse, or verify user-generated content." },
    { number: "5", title: "Data Security", text: "We implement commercially reasonable administrative, technical, and organizational safeguards to help protect your information. However, no website, software platform, cloud provider, or internet transmission can be guaranteed to be completely secure. By using Dominion Writer, you acknowledge and accept these inherent risks." },
    { number: "6", title: "Data Retention", text: "We retain personal information only for as long as reasonably necessary to: Maintain your account, Provide services, Resolve disputes, Enforce agreements, Meet legal obligations, Maintain financial records where required by law. Information may be retained longer where required by applicable law." },
    { number: "7", title: "Data Deletion Requests", text: "You may request deletion of your Dominion Writer account at any time. Requests must be submitted to: admin@dominionwriter.com. After verifying your identity, Dominion Writer will make reasonable efforts to remove your personal information, subject to applicable legal, accounting, security, or operational retention requirements. Deleting your Dominion Writer account does not delete data held by third-party payment processors or AI providers. Those accounts must be managed directly with the applicable provider." },
    { number: "8", title: "Children's Privacy", text: "Dominion Writer is intended for individuals who are at least 18 years of age or the age of majority in their jurisdiction. We do not knowingly collect personal information from children. If we become aware that such information has been collected unintentionally, we will take reasonable steps to delete it." },
    { number: "9", title: "International Users", text: "If you access Dominion Writer from outside Canada, you understand that your information may be processed or stored in jurisdictions where our service providers operate. By using the platform, you consent to such processing where permitted by law." },
    { number: "10", title: "Acceptable Use Policy", text: "Dominion Writer exists to provide writers with software that connects to their own AI API. Users agree to use the platform lawfully and responsibly. Users may not: Attempt unauthorized access to the platform, Reverse engineer the software, Copy or reproduce proprietary code, Resell Dominion Writer access, Redistribute the software, Upload malware or malicious code, Interfere with website security, Abuse or overload platform infrastructure, Circumvent security measures, Share stolen API credentials, Use another person's account without authorization. Users are solely responsible for all content generated using Dominion Writer. Dominion Writer does not review or approve user content before publication. Violation of this Acceptable Use Policy may result in immediate suspension or termination of access without refund." },
    { number: "11", title: "Cookie Policy", text: "Dominion Writer uses cookies and similar technologies to improve user experience and website functionality. Cookies may be used to: Maintain login sessions, Remember preferences, Improve website performance, Analyze website traffic, Detect security threats, Prevent fraudulent activity. Most web browsers allow users to manage or disable cookies. Disabling cookies may reduce or prevent certain website features from functioning correctly. By continuing to use Dominion Writer, you consent to the use of cookies as described in this policy." },
    { number: "12", title: "Disclaimer", text: "Dominion Writer provides software only. We do not provide: Legal advice, Financial advice, Accounting advice, Tax advice, Medical advice, Professional consulting, Investment advice. Content generated using third-party AI providers may contain inaccuracies, omissions, hallucinations, outdated information, or other errors. Users are solely responsible for reviewing, editing, fact-checking, and verifying all AI-generated content before relying on or publishing it. Dominion Writer does not guarantee: Accuracy, Completeness, Reliability, Availability, Suitability, Fitness for a particular purpose, Error-free operation, Continuous uptime. Use of the platform is entirely at your own risk." },
    { number: "13", title: "Intellectual Property", text: "The Dominion Writer website, software, source code, user interface, branding, graphics, workflows, databases, features, and proprietary technology are the exclusive intellectual property of Mr. Nghia Nguyen. Users may not: Copy the software, Reverse engineer the software, Decompile the software, Modify the software, Resell the platform, Redistribute the platform, Create derivative works, Remove copyright notices, Use Dominion Writer branding without written permission. Unauthorized use may result in legal action." },
    { number: "14", title: "Limitation of Liability", text: "To the fullest extent permitted by law, Dominion Writer and Mr. Nghia Nguyen shall not be liable for any direct, indirect, incidental, consequential, special, or punitive damages arising from: Use of the platform, AI-generated content, Third-party AI providers, API failures, Billing disputes with AI providers, Data loss, Service interruptions, Security incidents beyond our reasonable control, User-generated content, Decisions made based on AI-generated information. Users assume all risks associated with using the platform." },
    { number: "15", title: "Changes to This Privacy Policy", text: "Dominion Writer may update this Privacy Policy at any time. Changes become effective immediately upon publication on the Dominion Writer website. Continued use of the platform after changes are posted constitutes acceptance of the revised policy." },
    { number: "16", title: "Governing Law", text: "This Privacy Policy and all matters relating to Dominion Writer shall be governed by the laws of the Province of Alberta and the federal laws of Canada applicable therein. Any dispute, claim, or legal proceeding arising out of or relating to this Privacy Policy or your use of Dominion Writer shall be brought exclusively before the courts located in Calgary, Alberta, Canada, and you consent to the exclusive jurisdiction of those courts." }
  ]
}

export const termsContent = {
  title: "Dominion Writer User Agreement",
  effectiveDate: "Immediately upon Purchase",
  contact: "admin@dominionwriter.com",
  owner: "Mr. Nghia Nguyen",
  sections: [
    { number: "1", title: "Company Information", text: "Dominion Writer is owned and operated by Mr. Nghia Nguyen (\"Owner\"). For questions regarding this Agreement, contact: Email: admin@dominionwriter.com" },
    { number: "2", title: "Acceptance of Agreement", text: "This Agreement becomes legally effective immediately upon successful payment for a Dominion Writer Lifetime Plan. By completing your purchase, you agree to all terms contained herein. If you do not agree with these terms, do not purchase or use Dominion Writer." },
    { number: "3", title: "Lifetime Membership", text: "Your purchase grants you a Lifetime Membership to Dominion Writer, subject to continued compliance with this Agreement. A Lifetime Membership provides ongoing access to the Dominion Writer platform for as long as the service continues to operate. Dominion Writer reserves the right to update, improve, modify, or discontinue features, functionality, integrations, or services at any time without prior notice." },
    { number: "4", title: "No Refund Policy", text: "All sales are final. Because Dominion Writer provides immediate access to proprietary software and digital services, all purchases are non-refundable. By completing your purchase, you expressly acknowledge and agree that:\n\n• No refunds will be provided.\n• No partial refunds will be issued.\n• No exchanges or credits will be granted.\n• Dissatisfaction with third-party AI providers does not qualify for a refund.\n• Failure to use the platform does not qualify for a refund." },
    { number: "5", title: "Bring Your Own AI API", text: "Dominion Writer operates as a platform that allows users to connect and utilize their own Artificial Intelligence (AI) provider through their personal API credentials. Users are solely responsible for:\n\n• Obtaining their own AI API\n• Selecting their preferred AI provider\n• Maintaining their API credentials\n• Paying all AI provider fees\n• Purchasing API credits\n• Monitoring API usage\n• Managing AI provider subscriptions\n\nDominion Writer does not sell AI usage, AI credits, API access, or language model services. Dominion Writer simply provides software that enables writers to utilize their own AI API without the limitations commonly imposed by subscription-based AI writing platforms." },
    { number: "6", title: "Third-Party AI Services", text: "Dominion Writer does not own, operate, manage, endorse, or control any third-party AI provider. Examples may include, but are not limited to:\n\n• OpenAI\n• Anthropic\n• Google\n• xAI\n• Mistral\n• DeepSeek\n• Cohere\n• Any future AI provider chosen by the user\n\nThe Owner shall not be liable for:\n\n• AI-generated outputs\n• AI errors\n• Hallucinations\n• Downtime\n• API outages\n• API billing\n• API pricing\n• API security\n• API rate limits\n• Credit depletion\n• Suspension of API accounts\n• Changes made by AI providers\n\nAny issues relating to an AI provider must be addressed directly with that provider." },
    { number: "7", title: "User Responsibility", text: "You are solely responsible for all content generated, edited, published, distributed, or otherwise created through Dominion Writer. This includes, but is not limited to:\n\n• Books\n• Articles\n• Blogs\n• Marketing materials\n• Fiction\n• Non-fiction\n• Emails\n• Sales copy\n• Websites\n• Advertising\n• Social media\n• Academic work\n• Business documents\n• Scripts\n\nYou agree to comply with all applicable local, provincial, state, federal, and international laws." },
    { number: "8", title: "No Liability for User Content", text: "Dominion Writer provides software tools only. The Owner is not responsible for:\n\n• Topics selected by users\n• Opinions expressed by users\n• AI-generated content\n• Published materials\n• Copyright violations committed by users\n• Trademark violations committed by users\n• Defamation\n• Plagiarism\n• Misrepresentation\n• Illegal content\n• Offensive material\n• Financial advice\n• Medical advice\n• Legal advice\n• Political content\n• Religious content\n\nUsers assume all responsibility for any content they create using Dominion Writer." },
    { number: "9", title: "Intellectual Property", text: "All software, source code, databases, workflows, user interfaces, branding, graphics, functionality, features, algorithms, designs, and proprietary technology associated with Dominion Writer are the exclusive intellectual property of Mr. Nghia Nguyen. No ownership rights are transferred to users. You may not:\n\n• Copy the software\n• Reproduce the software\n• Modify the software\n• Reverse engineer the software\n• Decompile the software\n• Disassemble the software\n• Attempt to discover the source code\n• License the software\n• Sell the software\n• Resell access to the software\n• Create derivative works\n• Mirror the platform\n• Redistribute the platform\n• Build competing software using Dominion Writer's proprietary technology\n\nAny unauthorized use constitutes a violation of applicable intellectual property laws and may result in legal action." },
    { number: "10", title: "Account Security", text: "Users are responsible for maintaining the confidentiality of their account credentials and AI API keys. Dominion Writer is not liable for unauthorized access resulting from:\n\n• Weak passwords\n• Shared accounts\n• Stolen credentials\n• Compromised API keys\n• User negligence." },
    { number: "11", title: "Data Deletion Requests", text: "Users may request deletion of their Dominion Writer profile at any time. To request deletion, email: admin@dominionwriter.com. Following verification, Dominion Writer will make reasonable efforts to delete the user's account information, subject to any legal or operational record-retention requirements. Deletion of a Dominion Writer account does not affect accounts, subscriptions, billing, or data held by any third-party AI provider. Users remain responsible for managing those services directly." },
    { number: "12", title: "Disclaimer of Warranties", text: "Dominion Writer is provided on an \"AS IS\" and \"AS AVAILABLE\" basis. To the fullest extent permitted by law, Dominion Writer makes no warranties regarding: Availability, Accuracy, Reliability, Performance, AI outputs, Compatibility, Error-free operation, Uninterrupted service. Use of the platform is entirely at your own risk." },
    { number: "13", title: "Limitation of Liability", text: "To the maximum extent permitted by applicable law, neither Dominion Writer nor Mr. Nghia Nguyen shall be liable for any direct, indirect, incidental, consequential, special, punitive, or exemplary damages arising out of or relating to:\n\n• Use of the platform\n• Inability to use the platform\n• AI-generated content\n• Third-party AI providers\n• Loss of data\n• Lost profits\n• Business interruption\n• API failures\n• AI inaccuracies\n• User-generated content\n• Security breaches outside Dominion Writer's reasonable control\n\nYour sole remedy is to discontinue use of the platform." },
    { number: "14", title: "Indemnification", text: "You agree to defend, indemnify, and hold harmless Dominion Writer, Mr. Nghia Nguyen, affiliates, contractors, and representatives from any claims, liabilities, damages, losses, legal fees, costs, or expenses arising from:\n\n• Your use of the platform\n• Your generated content\n• Your AI API usage\n• Your violation of this Agreement\n• Your violation of applicable laws\n• Claims brought by third parties related to your activities." },
    { number: "15", title: "Suspension or Termination", text: "Dominion Writer reserves the right to suspend or terminate accounts that:\n\n• Violate this Agreement\n• Abuse the platform\n• Engage in fraudulent activity\n• Attempt unauthorized access\n• Reverse engineer the software\n• Interfere with platform security\n• Resell or redistribute Dominion Writer without authorization\n\nTermination for violation of this Agreement does not entitle the user to a refund." },
    { number: "16", title: "Governing Law and Jurisdiction", text: "This Agreement shall be governed by and interpreted in accordance with the laws of the Province of Alberta and the federal laws of Canada applicable therein. Any dispute, claim, legal proceeding, or litigation arising out of or relating to Dominion Writer or this Agreement shall be brought exclusively in the courts located in Calgary, Alberta, Canada. By using Dominion Writer, you expressly consent to the exclusive jurisdiction and venue of those courts." },
    { number: "17", title: "Changes to This Agreement", text: "Dominion Writer reserves the right to modify or update this Agreement at any time. Updated versions become effective upon publication on the Dominion Writer website. Continued use of the platform after changes constitutes acceptance of the revised Agreement." },
    { number: "18", title: "Entire Agreement", text: "This Agreement constitutes the entire agreement between Dominion Writer and the user regarding use of the platform and supersedes any prior agreements, communications, or understandings. If any provision of this Agreement is held invalid or unenforceable, the remaining provisions shall continue in full force and effect." }
  ]
}